apiVersion: v1
kind: ServiceAccount
metadata:
  name: rayjob-scheduler-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rayjob-scheduler-role
  namespace: default
rules:
# Permissions for RayJob resources
- apiGroups: ["ray.io"]
  resources: ["rayjobs"]
  verbs: ["create", "delete", "get", "list", "update", "patch", "watch"]
# Permissions for Kubernetes Job resources
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "update", "patch", "watch"]
# Permissions for Pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "update", "patch", "watch"]
# Permissions for Pods logs
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rayjob-scheduler-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rayjob-scheduler-role
subjects:
- kind: ServiceAccount
  name: rayjob-scheduler-account
  namespace: default
