apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: cpu-tuning-job
spec:
  entrypoint: python /app/stats_forecast_tune.py
  shutdownAfterJobFinishes: true
  rayClusterSpec:
    rayVersion: '2.9.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          tolerations: # Tolerations for the taint on the node pool
            - key: "dedicated"
              operator: "Equal"
              value: "fastpool"
              effect: "NoSchedule"
          nodeSelector:
            hardware: highcpu
          imagePullSecrets:
            - name: acr-secret
          containers:
            - name: ray-head
              image: chiemoadprd.azurecr.io/license_forecast:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                requests:
                  cpu: "15"
                limits:
                  cpu: "16"
              env:
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: my-service-principal-secret
                      key: tenantId
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: my-service-principal-secret
                      key: clientId
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: my-service-principal-secret
                      key: clientSecret
    workerGroupSpecs:
      - replicas: 24
        groupName: small-group
        rayStartParams: {}
        template:
          spec:
            tolerations: # Tolerations for the taint on the node pool
              - key: "dedicated"
                operator: "Equal"
                value: "fastpool"
                effect: "NoSchedule"
            nodeSelector:
              hardware: highcpu
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: "ray.io/group"
                      operator: In
                      values:
                      - small-group
                  topologyKey: "kubernetes.io/hostname"
            imagePullSecrets:
              - name: acr-secret
            containers:
              - name: ray-worker
                image: chiemoadprd.azurecr.io/license_forecast:latest
                imagePullPolicy: Always
                resources:
                  requests:
                    cpu: "15"
                  limits:
                    cpu: "16"
                env:
                  - name: AZURE_TENANT_ID
                    valueFrom:
                      secretKeyRef:
                        name: my-service-principal-secret
                        key: tenantId
                  - name: AZURE_CLIENT_ID
                    valueFrom:
                      secretKeyRef:
                        name: my-service-principal-secret
                        key: clientId
                  - name: AZURE_CLIENT_SECRET
                    valueFrom:
                      secretKeyRef:
                        name: my-service-principal-secret
                        key: clientSecret
