apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: gpu-predict-job
spec:
  entrypoint: python /app/neural_forecast_predict.py
  shutdownAfterJobFinishes: true
  rayClusterSpec:
    rayVersion: '2.9.0'
    headGroupSpec:
      rayStartParams:
        num-cpus: "14"
        num-gpus: "1"
        dashboard-host: '0.0.0.0'
      template:
        spec:
          tolerations: # Tolerations for the taint on the node pool
            - key: "dedicated"
              operator: "Equal"
              value: "gpupool"
              effect: "NoSchedule"
          nodeSelector:
            hardware: gpu
          imagePullSecrets:
            - name: acr-secret
          containers:
            - name: ray-head
              image: chiemoadprd.azurecr.io/license_forecast:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                requests:
                  cpu: "14"
                  nvidia.com/gpu: "1"
                limits:
                  cpu: "14"
                  nvidia.com/gpu: "1"
              env:
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: my-service-principal-secret
                      key: tenantId
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: my-service-principal-secret
                      key: clientId
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: my-service-principal-secret
                      key: clientSecret
              volumeMounts:
                - mountPath: "/mnt/tuning_files"
                  name: tuning-storage
    workerGroupSpecs:
      - replicas: 3
        groupName: gpu-group
        rayStartParams:
          num-cpus: "14"
          num-gpus: "1"
        template:
          spec:
            tolerations: # Tolerations for the taint on the node pool
              - key: "dedicated"
                operator: "Equal"
                value: "gpupool"
                effect: "NoSchedule"
            nodeSelector:
              hardware: gpu
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: app # Use an appropriate label key that exists on your pods
                      operator: In
                      values:
                      - ray-worker
                  topologyKey: "kubernetes.io/hostname"
            imagePullSecrets:
              - name: acr-secret
            containers:
              - name: ray-worker
                image: chiemoadprd.azurecr.io/license_forecast:latest
                imagePullPolicy: Always
                resources:
                  requests:
                    cpu: "14"
                    nvidia.com/gpu: "1"
                  limits:
                    cpu: "14"
                    nvidia.com/gpu: "1"
                env:
                  - name: AZURE_TENANT_ID
                    valueFrom:
                      secretKeyRef:
                        name: my-service-principal-secret
                        key: tenantId
                  - name: AZURE_CLIENT_ID
                    valueFrom:
                      secretKeyRef:
                        name: my-service-principal-secret
                        key: clientId
                  - name: AZURE_CLIENT_SECRET
                    valueFrom:
                      secretKeyRef:
                        name: my-service-principal-secret
                        key: clientSecret
