name: my_ml_env
channels:
  - pytorch  
  - nvidia  
  - defaults
dependencies:
  - python==3.10
  - ninja
  - pip==23.0.1
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - packaging
  - pip:
      - scikit-learn
      - numpy
      - pyarrow
      - pandas
      - azure-keyvault-secrets
      - accelerate==0.25.0
      - datasets
      - peft
      - evaluate
      - azure-ai-ml
      - azureml-core
      - sentencepiece
      - rouge-score
      - mlflow
      - azureml-mlflow
      - dm-tree
      - ray[air]==2.8.1
      - tokenizers
      - azureml-dataset-runtime
      - azure-storage-blob
      - transformers==4.36.2
      - flash-attn
      - aiohttp
      - asyncio
      - nest-asyncio
      - azure-storage-file-datalake
      - azure-identity
      - trl==0.7.4
      - bitsandbytes
      - deepspeed==0.12.5
      - pydantic==1.10.13
      - grpcio
      - einops